version: '3'

services:
  proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - 8000:8000
    command: bash -c "gunicorn server.wsgi -b 0.0.0.0:8000 && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/app
